apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-system-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: chat-system
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-system
        branch: {{ git_branch }}
    spec:
      containers:
        - name: chat-system-container
          image: ruchira088/chat-system:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: chat-system-data-config-map
            - secretRef:
                name: chat-system-secrets
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: http4s-port
              containerPort: 8000
          volumeMounts:
            - mountPath: /opt/data
              name: file-config-map
      volumes:
        - name: file-config-map
          configMap:
            name: chat-system-file-config-map

