apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-system-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: chat-system-tls
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: chat-system-service
                port:
                  name: http4s-port