version: "3.8"

services:

  chat-api:
    image: chat-api:latest
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/chat-system"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "my-redis-password"

  postgres:
    image: postgres
    #    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: "pg_isready -U admin -d chat-system"
      start_period: 10s
      interval: 10s
      timeout: 5s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "chat-system"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  redis:
    image: redis
    command: "redis-server --requirepass my-redis-password"
    healthcheck:
      test: "redis-cli ping"
      start_period: 1s
      interval: 2s
      timeout: 1s
    ports:
      - 6379:6379