version: "3.8"

services:

  chat-system:
#    build: .
    image: chat-system:latest
    ports:
      - 8000:8000
#      - 5005:5005
    volumes:
      - "./src/main/resources/logback.xml:/opt/data/logback.xml"
#      - "~/.sbt:/root/.sbt"
#      - "~/Library/Caches/Coursier:/root/.cache/coursier" # MacOS Coursier cache
#      #      - "~/.cache/coursier:/root/.cache/coursier" # Linux Coursier cache
#      #      - "~/AppData/Local/Coursier/Cache:/root/.cache/coursier" # Windows Coursier cache
#      - ".:/opt/chat-system"
#      - "/opt/chat-system/target"
#      - "/opt/chat-system/project/target"
#      - "/root/.sbt/1.0/plugins"
  postgres:
    image: postgres
    #    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: "pg_isready -U admin -d chat-system"
      start_period: 10s
      interval: 10s
      timeout: 5s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "chat-system"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  redis:
    image: redis
#    command: "redis-server --requirepass my-redis-password"
    healthcheck:
      test: "redis-cli ping"
      start_period: 1s
      interval: 2s
      timeout: 1s
    ports:
      - 6379:6379