FROM openjdk:17-slim

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/chat-system

ADD chat-system-*.tgz .

EXPOSE 8000

CMD [ "/opt/chat-system/bin/chat-system" ]
