FROM openjdk:17-slim

LABEL org.opencontainers.image.source https://github.com/ruchira088/chat-api

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/chat-api

ADD chat-api-*.tgz .

EXPOSE 8000

CMD [ "/opt/chat-api/bin/chat-api" ]
