FROM openjdk:17-slim

LABEL org.opencontainers.image.source https://github.com/ruchira088/chat-api

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/chat-migration-app

ADD chat-migration-app-*.tgz .

CMD [ "/opt/chat-migration-app/bin/chat-migration-app" ]
